name: bera

data:
  path: data/beer_dataset.csv # The full path to the dataset 
  split_size: 168 # Train split size 
  target: Beer Production (ML)

# Visualization configurations
visualizer:
  plot_path: plots/
  decomposition_model: additive # Decomposition plot [additive, multiplicative]
  style_theme: seaborn-v0_8-whitegrid
  dpi: 150
  default_figsize: !tuple [14, 7]
  acf_lags: 40


# Models configurations
models:
  # 1. Classical Decomposition
  decompose:
    model: multiplicative # Model type [additive, multiplicative]
    period: 12 # Seasonal period
  # 2. Holt-Winters model
  exponential_smoothing:
    trend: add # Trend component [add, mul]
    seasonal: mul # Seasonal component [add, mul]
    seasonal_periods: 12
  # 3. Seasonal ARIMA model
  sarima:
    p: 1
    d: 1
    q: 1
    P: 1
    D: 1
    Q: 1
    s: 1

# Scoring metrics
scoring: 
  mae: true 
  mse: true
  rmse: true
  mape: true
